### ISSUE TITLE
Reference RFC 7515 for unpadded Base64 encoding

### ISSUE THREAD

**Issue by ghost** [martinthomson/http-encryption#8]
Just an editorial nit. If we're going to disallow padding in the headers, should we refer to the definition of "Base64url Encoding" in RFC 7515, Section 2?

RFC 4648 suggests padding is required "unless the specification referring to this document explicitly states otherwise."

**Comment by martinthomson** [comment]
Good idea.

I probably need to add a pointer to the real repo somewhere.  See @httpwg/http-extensions
